### PR TITLE
chore: update version constraints

### PR DESCRIPTION
**Pull request by iamar7**
### Description

https://github.ibm.com/GoldenEye/issues/issues/4915

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Ak-sky** [comment]
PR is failing due to the wrong(old way of passing) location whenn CBR zones are getting created for the serviceRef, this needs to be addressed - https://github.com/terraform-ibm-modules/terraform-ibm-cbr/issues/426

```
│         "errors": [
│             {
│                 "code": "invalid_service_ref_location",
│                 "message": "Invalid `serviceRef` location: `us-south` is invalid. Allowed values for each service can be found using the list service reference targets API.",
│                 "target": {
│                     "name": "value",
│                     "type": "field",
│                     "value": "serviceName=cloud-object-storage,accountId=abac0df06b644a9cabc6e44f55b3880e,location=us-south"
│                 }
│             }
```

**Comment by ocofaigh** [comment]
Addressed in a different Pr already

**Pull request closed without merging**
