### PR TITLE
fix: add validation for source/target guid

### PR DESCRIPTION
**Pull request by MatthewLemmond**
### Description
change in provider no longer accepts CRN or GUID, only GUID. Added validation to example with regex and clarified usage block to specify GUID

Note: the validation doesn't actually work at plan time due to the GUID/CRN being known after apply, but adding the validation does give us the ability to provide an error message clarifying why this failure occurred.

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Previously the module accepted either CRN or GUID to be passed for the `source_resource_instance_id` and `target_resource_instance_id`, this has changed to only accept the GUID as valid input for this field in the `var.service_map` variable.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by MatthewLemmond** [comment]
PR also includes changes for two other automated PRs that are failing due to this change: https://github.com/terraform-ibm-modules/terraform-ibm-s2s-auth/pull/69 and https://github.com/terraform-ibm-modules/terraform-ibm-s2s-auth/pull/74.
skipped upgrade test due to the change being on the provider side the upgrade test is failing because the previous version is still passing a CRN to the provider causing the upgrade test to fail

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
