### PR TITLE
fix(deps): update to consume CBR module 1.23.0

### PR DESCRIPTION
**Pull request by MatthewLemmond**
### Description

Update to the latest CBR service profile to allow for selection of location for CBR zones and update the lowest required version of the provider to match

resolves https://github.com/terraform-ibm-modules/terraform-ibm-s2s-auth/issues/124
fixes the problems with s2s in https://github.com/terraform-ibm-modules/terraform-ibm-s2s-auth/pull/125

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Update the CBR module to 1.23.0

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by MatthewLemmond** [comment]
Upgrade test failed with
```
Actions: [update]
  DIFF:
    Before: 
      {"description":"cloud-object-storage-cbr-serviceref-zone-terraform"}
    After: 
      {"description":"cloud-object-storage-cbr-serviceref-zone"}
```

skipping upgrade test as this is just an update to the description coming from the CBR module

**Comment by MatthewLemmond** [comment]
will allow https://github.com/terraform-ibm-modules/terraform-ibm-s2s-auth/pull/125 to pass tests

**Review by toddgiguere — APPROVED** [review]

**Pull request merged**
